#
FROM node:16.5.0-alpine3.11 as main
#give name if youre going to use main on copy for example instead of 0

# WORK FOLDER
WORKDIR "/client"  

# Copy first the package json, else it will rerun ALL the installs, bad idea
COPY ./package.json ./
RUN npm install
COPY ./ ./
#expose is beanstalk

RUN npm run build

FROM nginx 
COPY --from=main  /client/build /usr/share/nginx/html 