sudo: required
services:
- docker
before_install:
- docker-compose build
script:
- docker-compose run -e CI=true client npm run test
deploy:
  provider: heroku
  on:
    branch: test
  api_key:
    secure: Aq7h3q+kaKCNdQzEYvg3gNVWyVW20XLLAKo5D2Pj3EcH2C8oUQUSa79lP81jFy3GMdjSNPj320YC9k1ACoYw328Mb/B6c9+uwyRmrBcf24Rg4c1yGxIPjIVPXSmnHRbTkOV74qi3HzhPE/EQMzgpa/8lwiLK0InbIHiI/qDaZ+u0TTwDajWY8NPzYI2L19OBC1SA90xT3SlX83zR/JqepblBBa77DwGK9GoeJ0kI180oMCJzd9IY2IKOKuBujNvyvFIFuHeTM2go5yxHqUbhFi7TkgjpkcTzQK3DslR/ZFOZ6waUMYWWfdjzCfJ7BPT9xT0a+7Rp9sCH8sTb/jcJYJL1I5u3pAoSmvIsjC8jSu8p7tcamxNnDU9lKDm8yGOACoM9eNtjRMApQVll7o3GasYkoNSx5p/tBaNc0+jLlAEqDNsPj7XwurmZOoqLPLI3uYwPqq1wCiWeymzydqqewW0gvTPfDW+8HUrn5KNpHd2894JcuK5XDzB2W90tzPBNxuKWKOszPFa8ASlNEMnR42fNG4FVXsOCXh9Bt35Yu/9Mnms5nyDbROZLp2GCN8FU5WSBwMASHbHqRksHRiu2+g2fjdmrjVQq3FroPn6aUNV2EOPCmwniBvX19B/ScjQNjxllvbi3sdC3F3hQ13j+RzfHGnVruqvIUE5pn3SqDRc=
  app: dockerc
##