version: "3"
services:
    # Virou Api por causa do nginx, ele tem uma keyword 'server' já implantada e poderia ocorrer incompatibilidade
    client:
        stdin_open: true
        build:
            context: "./client"
            dockerfile: Dockerfile
        restart: on-failure
        volumes:
            - /client/node_modules
            - ./client:/client
        # command: npm run start # trocar para test caso for para o Travis, comentar tudo SE FOR PRA UTILIZAR O NGINX
            ### Importante lembrar ; nginx quando estiver em dev, test quando for build
    nginx:
        restart: always
        build: 
            context: ./nginx
            dockerfile: Dockerfile
        ports: 
            - "8000:80"
        environment:
            - PORT:80
            
    