FROM php:7.4-apache

WORKDIR '/client'
RUN apt-get update
RUN apt-get install gettext-base
RUN docker-php-ext-install mysqli && docker-php-ext-enable mysqli
# COPY "/php/src" "/var/www/html/"
RUN mkdir /usr/local/src/ses

# Esse comando talvez salve o problema do php-ext não funcionar no travis?
RUN chown -R www-data:www-data /usr/local/src/ses 
#########

COPY ./php.ini /usr/local/etc/php
COPY ./scrip.php ./
EXPOSE 80
CMD /bin/bash -c "envsubst '\$herokusqlHost,\$herokusqlDatabase,\$herokusqlPassword,\$herokusqlUser' < /var/www/html/php/conexao.php > /var/www/html/php/conexao.php" && apachectl -D FOREGROUND

