FROM python:3.6.14-alpine3.14

WORKDIR /api
COPY ./ ./

RUN apk add --no-cache --virtual .build-deps g++ python3-dev libffi-dev openssl-dev && \
    apk add --no-cache --update python3 
    
RUN pip install -r requirements.txt
RUN chmod +x ./flask-run.sh

CMD ["python3.6","-u","./app.py"]

